apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-image-tag
  namespace: tekton-pipelines
spec:
  params:
    - name: destination-branch
      description: Repository destination branch.
      type: string
    - name: merge-commit-hash
      type: string
  workspaces:
    - name: repository
    - name : ssh-directory

  steps:
    - image: alpine
      name: replace-tag-on-deployment
      env:
      - name: MERGE_COMMIT_HASH
        value: $(params.merge-commit-hash)
      script: |
        echo "----------- Instalando dependencias -----------"
        apk add bash sed

        #!/bin/bash
        source .env

        echo "----------- Atualizando tag da imagem -----------"
        sed -i "s|142401413602.dkr.ecr.sa-east-1.amazonaws.com/ecr-.*|142401413602.dkr.ecr.sa-east-1.amazonaws.com/ecr-$APPLICATION_NAME:$MERGE_COMMIT_HASH|" k8s/deployment.yaml

        if [ $? -eq 0 ]
        then
            echo "A tag imagem da aplicacao usada no deployment foi atualizada com sucesso"
            exit 0
        else
            echo "Falha ao atualizar tag da imagem da aplicação"
            exit 1
        fi
      securityContext:
        privileged: true
      workingDir: "$(workspaces.repository.path)"

    - image: alpine
      name: push-modification-to-git
      env:
      - name: WORKSPACE_SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      - name: MERGE_COMMIT_HASH
        value: $(params.merge-commit-hash)
      script: |
        echo "----------- Instalando dependencias -----------"
        apk add bash sed git

        #!/bin/bash

        cp -R "${WORKSPACE_SSH_DIRECTORY_PATH}" /tekton/home/.ssh
        chmod 700 /tekton/home/.ssh
        chmod -R 400 /tekton/home/.ssh/*

        echo "----------- Subindo modificação para o repositório git -----------"
        ls -la
        # git add . && git commit -m "chore(deploy): updating image tag to '$MERGE_COMMIT_HASH'"
      securityContext:
        privileged: true
      workingDir: "$(workspaces.ssh-directory.path)"
