apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-image-tag
  namespace: tekton-pipelines
spec:
  params:
    - name: destination-branch
      description: Repository destination branch.
      type: string
    - name: merge-commit-hash
      type: string

  workspaces:
    - name: repository

  steps:
    - image: alpine
      securityContext:
        privileged: true
      name: replace-tag-on-deployment
      script: |
        echo "----------- Instalando dependencias -----------"
        apk add bash sed

        #!/bin/bash
        source .env
        MERGE_COMMIT_HASH="$(params.merge-commit-hash)"

        echo "----------- Atualizando tag da imagem -----------"
        sed -i "s|142401413602.dkr.ecr.sa-east-1.amazonaws.com/ecr-.*|142401413602.dkr.ecr.sa-east-1.amazonaws.com/ecr-$APPLICATION_NAME:$MERGE_COMMIT_HASH|" k8s/deployment.yaml

        if [ $? -eq 0 ]
        then
            echo "A tag imagem da aplicacao usada no deployment foi atualizada com sucesso"
            exit 0
        else
            echo "Falha ao atualizar tag da imagem da aplicação"
            exit 1
        fi

      workingDir: "$(workspaces.repository.path)"

    - image: alpine
      securityContext:
        privileged: true
      name: push-modification-to-git
      script: |
        echo "----------- Instalando dependencias -----------"
        apk add bash sed git

        #!/bin/bash
        source .env

        echo "----------- Subindo modificação para o repositório git -----------"
        cat k8s/deployment.yaml
        git status

      workingDir: "$(workspaces.repository.path)"
