apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-pipeline-server
  namespace: tekton-pipelines
  annotations:
    konghq.com/https-redirect-status-code: '302'
    kubernetes.io/ingress.class: kong
    konghq.com/protocols: https
    konghq.com/strip-path: 'true'
spec:
  rules:
    - host: tekton-pipeline.owill.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tekton-pipeline
                port:
                  number: 8080
