apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-pipelines-server
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: tekton-pipeline.owill.com.br
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: el-github-pull-request
                port:
                  number: 8080
