apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-go
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
    - name: destination-branch
  workspaces:
    - name: repository
    - name: artifacts
    - name: ssh-directory

  tasks:
    - name: setup
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.destination-branch)
      taskRef:
        name: setup
      workspaces:
        - name: repository
          workspace: repository
        - name: ssh-directory
          workspace: ssh-directory

    - name: lint
      runAfter:
        - setup
      taskRef:
        name: golangci-lint
      workspaces:
        - name: repository
          workspace: repository
