apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-test
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
    - name: current-branch
  workspaces:
    - name: repository
    - name: artifacts
    - name: ssh-directory

  tasks:
    - name: setup
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.current-branch)
      taskRef:
        name: setup
      workspaces:
        - name: repository
          workspace: repository
        - name: ssh-directory
          workspace: ssh-directory

    - name: golangci-lint
      runAfter:
        - setup
      taskRef:
        name: golangci-lint
      workspaces:
        - name: repository
          workspace: repository
    
    - name: golang-security-checker
      runAfter:
        - setup
      taskRef:
        name: golang-security-checker
      workspaces:
        - name: repository
          workspace: repository
    
    - name: golang-test
      runAfter:
        - setup
      taskRef:
        name: golang-test
      workspaces:
        - name: repository
          workspace: repository
