apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-pull-request-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: commit-sha
    - name: repository_full_name
  workspaces:
    - name: ssh-credentials
    - name: git-source
  tasks:
    - name: set-status
      taskRef:
        kind: Task
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository_full_name)
        - name: SHA
          value: $(params.commit-sha)
        - name: DESCRIPTION
          value: "Build has started"
        - name: STATE
          value: pending
        - name: TARGET_URL
          value: "http://tekton-dashboard-dev.owill.com.br/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)"
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: ssh-directory
          workspace: ssh-credentials
        - name: repository
          workspace: git-source
    - name: metadata-exporter
      runAfter: ["fetch-source"]
      taskRef:
        name: metadata-exporter
      workspaces:
        - name: repository
          workspace: git-source
    - name: build
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: git-source
      params:
      - name: IMAGE
        value: "876897421480.dkr.ecr.us-west-1.amazonaws.com/tekton"
  finally:
    - name: final-set-status
      taskRef:
        kind: Task
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository_full_name)
        - name: SHA
          value: $(params.commit-sha)
        - name: DESCRIPTION
          value: "Build has started"
        - name: STATE
          value: "$(tasks.status)"
        - name: TARGET_URL
          value: "http:///tekton-dashboard-dev.owill.com.br/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)"
