apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-pull-request
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-interceptor-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: github-pull-request-binding
      template:
        ref: github-pull-request-pipeline-template
