apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-ecr
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: repository

  steps:
    - image: 142401413602.dkr.ecr.sa-east-1.amazonaws.com/ecr-image-default-aws-cli:build
      name: verify-repository
      script: |
        #!/bin/bash
        cd /workspace/repository && source .env

        echo "----------- Validando dados do metadata -----------"
        #Replace APPLICATION_NAME
        if [ -z "${APPLICATION_NAME}" ]; then
            echo "Não encontrado a váriavel APPLICATION_NAME"
            exit 1
        else
            echo "Metadata validado."
            export APPLICATION_NAME=$(echo $APPLICATION_NAME | sed 's/_/-/g')
        fi

        echo "----------- Buscando repositório no ECR -----------"
        AWS_REGION=us-west-1
        AWS_ACCOUNT=876897421480
        ECR_REPO_NAME=ecr-$APPLICATION_NAME

        aws ecr describe-repositories --region $AWS_REGION --no-cli-pager --query "repositories[?repositoryName==\`$ECR_REPO_NAME\`][repositoryName]" --output text | grep -q "$ECR_REPO_NAME"

        if [ $? -eq 0 ]
        then
            echo "Repositório ECR encontrado com sucesso!"
        else
            echo "Repositório ECR não encontrado.."
            echo "Criando repositório $ECR_REPO_NAME"
            aws ecr create-repository --region $AWS_REGION --repository-name ${ECR_REPO_NAME} --no-cli-pager
            [ $? -ne 0 ] && echo "Erro ao criar o repositório $ECR_REPO_NAME" && exit
        fi
