apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-k8s
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
    - name: destination-branch
    - name: merge-commit-hash
  workspaces:
    - name: repository
    - name: artifacts
    - name: ssh-directory

  tasks:
    - name: setup
      when:
      - input: "$(params.destination-branch)"
        operator: in
        values: ["develop", "staging", "master", "main"]
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.destination-branch)
      taskRef:
        name: setup
      workspaces:
        - name: repository
          workspace: repository
        - name: ssh-directory
          workspace: ssh-directory

    - name: build-image
      when:
      - input: "$(params.destination-branch)"
        operator: in
        values: ["develop", "staging", "master", "main"]
      params:
        - name: destination-branch
          value: $(params.destination-branch)
      runAfter:
        - setup
      taskRef:
        name: build-image
      workspaces:
        - name: repository
          workspace: repository

    - name: update-image-tag
      when:
      - input: "$(params.destination-branch)"
        operator: in
        values: ["develop", "staging", "master", "main"]
      params:
        - name: destination-branch
          value: $(params.destination-branch)
        - name: merge-commit-hash
          value: $(params.merge-commit-hash)
      runAfter:
        - setup
      taskRef:
        name: update-image-tag
      workspaces:
        - name: repository
          workspace: repository
