apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
  namespace: tekton-pipelines
spec:
  steps:
    - name: build
      image: docker:19.03.8-dind
      securityContext:
        privileged: true
      script: |
        cd /workspace/repository
        ls
        apk add bash docker

        #!/bin/bash

        echo "----------- Gerando imagem da aplicação -----------"
        docker build -t tekton .

  workspaces:
    - name: repository
